-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: keycloak_user.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE keycloak_user (
  ku_uuid VARCHAR(36) NOT NULL,
  ku_user BIGINT NOT NULL,
  PRIMARY KEY(ku_uuid)
);

CREATE UNIQUE INDEX keycloak_user_user ON keycloak_user (ku_user);
