-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: keycloak_user.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/keycloak_user (
  ku_uuid VARCHAR(36) NOT NULL,
  ku_user BIGINT NOT NULL,
  UNIQUE INDEX keycloak_user_user (ku_user),
  PRIMARY KEY(ku_uuid)
) /*$wgDBTableOptions*/;
